services:
  backend:
    image: ${DOCKER_USERNAME}/scriptify_backend:${IMAGE_TAG}
    command:
      - /bin/bash
      - -c
      - |
        python manage.py makemigrations
        echo "Running database migrations..."
        python manage.py migrate --noinput --verbosity=2

        python manage.py migrate user
        python manage.py migrate scripts
        echo "Checking for any issues..."
        python manage.py check
        python manage.py runserver 0.0.0.0:8000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - scriptify_backend_network
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - scriptify_backend_data:/var/lib/postgresql/data
    restart: always
    networks:
      - scriptify_backend_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  scriptify_backend_network:
    driver: bridge

volumes:
  scriptify_backend_data: